# For live version
FROM burnysc2/python-sc2-docker:release-python_3.8-sc2_4.10

# Copy files from the current commit (the python-sc2 folder) to root
ADD . /root/python-sc2

# Install the python-sc2 library and its requirements (s2clientprotocol etc.) to python
WORKDIR /root/python-sc2
RUN pip install poetry
RUN poetry export -f requirements.txt --output requirements.txt --without-hashes
RUN pip install -r requirements.txt

# This will be executed during the container run instead:
# docker run test_image -c "poetry run python examples/protoss/cannon_rush.py"

ENTRYPOINT [ "/bin/bash" ]
