# THIS FILE WAS AUTOMATICALLY GENERATED BY generate_conversion_dicts_bot.py DO NOT CHANGE MANUALLY!
# ANY CHANGE WILL BE OVERWRITTEN

from sc2.ids.unit_typeid import UnitTypeId
from sc2.ids.ability_id import AbilityId

# from sc2.ids.buff_id import BuffId
from sc2.ids.upgrade_id import UpgradeId

# from sc2.ids.effect_id import EffectId

from typing import Dict, Set  # , List, Tuple, Union, Optional

UNIT_MORPH: Dict[UnitTypeId, AbilityId] = {
    UnitTypeId.INFESTORTERRAN: AbilityId.MORPHTOINFESTEDTERRAN_INFESTEDTERRANS,
    UnitTypeId.BANELING: AbilityId.MORPHZERGLINGTOBANELING_BANELING,
    UnitTypeId.BROODLORD: AbilityId.MORPHTOBROODLORD_BROODLORD,
    UnitTypeId.LURKERMP: AbilityId.MORPH_LURKER,
    UnitTypeId.RAVAGER: AbilityId.MORPHTORAVAGER_RAVAGER,
    UnitTypeId.GUARDIANMP: AbilityId.MORPHTOGUARDIANMP_MORPHTOGUARDIANMP,
    UnitTypeId.DEVOURERMP: AbilityId.MORPHTODEVOURERMP_MORPHTODEVOURERMP,
}
